name: CI
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Lint
        run: |
          ruff check --fix backend tests
          ruff format backend tests
      - name: Run tests
        run: pytest -q
      - name: Build Docker image
        run: docker build -t mini-netflix:${{ github.sha }} .
